import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, Lock, Sparkles, Wallet, X, Zap } from 'lucide-react';

type AllocationInput={p1Percent?:number;p2Percent?:number;p3Percent?:number;p4Percent?:number;p5Percent?:number;dexPercent?:number;unallocatedPercent?:number};
type Props={
 isOpen:boolean; onClose:()=>void;
 onConfirmPurchase:(tokenAmount:number,usdAmount:number,sellAlloc:{p1Percent:number;p2Percent:number;p3Percent:number;p4Percent:number;p5Percent:number;dexPercent:number;unallocatedPercent:number},txHash?:string,currency?:'USDT')=>Promise<void>|void;
 currentRate:number; walletConnected:boolean; walletAddress?:string; contractAddress?:string; receivingAddress?:string; minPurchaseUsd?:number; nxbcBalance?:number; usdtBalance?:number;
 activePhaseInfo?:{phaseNumber:number;name:string;shortName:string;totalSupply:number;tokensSold:number}; initialAllocation?:AllocationInput;
};
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const fmt=(v:number)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:6});

export const BuyTokenModal:React.FC<Props>=({isOpen,onClose,onConfirmPurchase,currentRate,walletConnected,walletAddress,minPurchaseUsd=0,usdtBalance=0,activePhaseInfo,initialAllocation})=>{
 const [usd,setUsd]=useState('');
 const [a,setA]=useState({p2:20,p3:30,p4:20,p5:15,dex:15});
 const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{if(!isOpen)return;setUsd('');setError('');setBusy(false);setA({p2:clamp(num(initialAllocation?.p2Percent,20)),p3:clamp(num(initialAllocation?.p3Percent,30)),p4:clamp(num(initialAllocation?.p4Percent,20)),p5:clamp(num(initialAllocation?.p5Percent,15)),dex:clamp(num(initialAllocation?.dexPercent,15))});},[isOpen,initialAllocation]);
 const purchaseUsd=Math.max(0,num(usd)); const tokens=currentRate>0?purchaseUsd/currentRate:0;
 const pct=a.p2+a.p3+a.p4+a.p5+a.dex; const pctOk=Math.abs(pct-100)<1e-7;
 const parts=useMemo(()=>{const p2=tokens*a.p2/100,p3=tokens*a.p3/100,p4=tokens*a.p4/100,p5=tokens*a.p5/100;const dex=Math.max(0,tokens-p2-p3-p4-p5);return {p2,p3,p4,p5,dex,total:p2+p3+p4+p5+dex};},[tokens,a]);
 const totalOk=tokens>0&&pctOk&&Math.abs(parts.total-tokens)<1e-9; const balanceOk=purchaseUsd<=num(usdtBalance)+1e-9;
 const can=walletConnected&&!!walletAddress&&purchaseUsd>0&&purchaseUsd>=num(minPurchaseUsd)&&balanceOk&&totalOk&&!busy;
 const set=(k:keyof typeof a,v:string)=>{setA(x=>({...x,[k]:clamp(num(v))}));setError('');};
 const preset=(v:any)=>{setA(v);setError('');};
 const confirm=async()=>{setError('');if(!walletConnected||!walletAddress)return setError('Please connect your Web3 wallet first.');if(purchaseUsd<=0)return setError('Enter a valid USDT purchase amount.');if(purchaseUsd<num(minPurchaseUsd))return setError(`Minimum purchase is $${num(minPurchaseUsd).toFixed(2)} USDT.`);if(!balanceOk)return setError('Insufficient USDT balance in the connected wallet.');if(!pctOk)return setError(`Please allocate exactly 100%. Current allocation is ${pct.toFixed(2)}%.`);if(!totalOk)return setError(`Allocation mismatch: ${fmt(parts.total)} / ${fmt(tokens)} NXBC.`);try{setBusy(true);await onConfirmPurchase(tokens,purchaseUsd,{p1Percent:0,p2Percent:a.p2,p3Percent:a.p3,p4Percent:a.p4,p5Percent:a.p5,dexPercent:a.dex,unallocatedPercent:0},undefined,'USDT');onClose();}catch(e:any){setError(e?.message||'Purchase could not be completed.');}finally{setBusy(false);}};
 if(!isOpen)return null;
 const cards=[['p2','Phase 2 Sell',.10,parts.p2],['p3','Phase 3 Sell',1,parts.p3],['p4','Phase 4 Sell',10,parts.p4],['p5','Phase 5 Sell',100,parts.p5]] as const;
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-2"><div className="w-full max-w-xl max-h-[96vh] overflow-y-auto rounded-3xl border border-amber-500/30 bg-[#070b16] text-white shadow-2xl">
  <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#070b16]/95 p-4"><div><div className="flex items-center gap-2 font-black"><Sparkles className="text-amber-300" size={18}/>BUY NXBC</div><div className="text-[11px] text-slate-400">Allocate 100% to future sell phases and/or DEX / LIVE.</div></div><button onClick={onClose}><X/></button></div>
  <div className="space-y-4 p-4">
   <div className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-4 flex justify-between"><div><div className="text-[10px] text-cyan-300">CURRENT PRESALE</div><b>{activePhaseInfo?.name||'Active Phase'}</b></div><div className="text-right"><div className="text-[10px] text-slate-400">RATE</div><b className="text-amber-300">${num(currentRate).toFixed(2)}</b></div></div>
   <div className="rounded-2xl border border-white/10 p-4"><label className="text-xs font-bold text-slate-400">USDT PURCHASE AMOUNT</label><div className="mt-2 flex items-center rounded-xl border border-purple-500/30 bg-[#0d1020] px-3"><Wallet size={18} className="mr-2 text-cyan-300"/><input value={usd} onChange={e=>{setUsd(e.target.value.replace(/[^\d.]/g,''));setError('')}} inputMode="decimal" placeholder="0.00" className="w-full bg-transparent py-4 text-xl font-black outline-none"/><b className="text-cyan-300">USDT</b></div><div className="mt-2 flex justify-between text-[11px] text-slate-500"><span>Wallet: {fmt(usdtBalance)} USDT</span><span>Receive: {fmt(tokens)} NXBC</span></div></div>
   <div className="rounded-2xl border border-cyan-500/20 bg-[#07141c] p-4"><div className="mb-3 flex justify-between"><div><div className="flex gap-2 font-black text-cyan-300"><Zap size={16}/>Quick 1-Click Split</div><span className="text-[10px] text-slate-500">Every preset = 100%</span></div><b className={pctOk?'text-emerald-300':'text-rose-300'}>{pct.toFixed(2)}%</b></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><button onClick={()=>preset({p2:20,p3:30,p4:20,p5:15,dex:15})} className="rounded-xl bg-cyan-500/10 p-3 text-[10px] font-black">20% SPLIT</button><button onClick={()=>preset({p2:50,p3:25,p4:10,p5:5,dex:10})} className="rounded-xl bg-amber-500/10 p-3 text-[10px] font-black">FAST CASH</button><button onClick={()=>preset({p2:10,p3:15,p4:15,p5:10,dex:50})} className="rounded-xl bg-emerald-500/10 p-3 text-[10px] font-black">HOLD 50%</button><button onClick={()=>preset({p2:0,p3:0,p4:0,p5:0,dex:100})} className="rounded-xl bg-purple-500/10 p-3 text-[10px] font-black">100% DEX / LIVE</button></div></div>
   {cards.map(([key,title,rate,tok])=><div key={key} className="rounded-2xl border border-white/10 bg-[#080d18] p-4"><div className="flex justify-between"><div><b>{title}</b><div className="text-[11px] text-slate-500">${rate.toFixed(2)} • {a[key].toFixed(2)}%</div></div><div className="text-right"><b className="text-emerald-300">{fmt(tok)} NXBC</b><div className="text-[10px] text-slate-500">${fmt(tok*rate)}</div></div></div><div className="mt-3 flex gap-2"><input type="number" min="0" max="100" step="0.01" value={a[key]} onChange={e=>set(key,e.target.value)} className="w-24 rounded-lg bg-[#101527] px-3 py-2 font-black outline-none"/><span className="py-2 text-xs">%</span><div className="mt-3 h-2 flex-1 rounded bg-white/5"><div className="h-full rounded bg-cyan-400" style={{width:`${a[key]}%`}}/></div></div></div>)}
   <div className="rounded-2xl border border-purple-500/30 bg-purple-500/5 p-4 flex justify-between"><div><b>DEX / LIVE</b><div className="text-[11px] text-slate-500">Not a presale FIFO order • held in wallet</div></div><div className="text-right"><b className="text-purple-300">{fmt(parts.dex)} NXBC</b><div className="text-[10px]">{a.dex.toFixed(2)}%</div></div></div>
   <div className={`rounded-2xl border p-4 ${totalOk?'border-emerald-500/30 bg-emerald-500/5':'border-rose-500/30 bg-rose-500/5'}`}><div className="flex justify-between"><b className="text-xs">ALLOCATION CHECK</b><b className={totalOk?'text-emerald-300':'text-rose-300'}>{pct.toFixed(2)}%</b></div><div className="mt-2 text-sm">Purchase: <b>{fmt(tokens)} NXBC</b></div><div className="text-sm">Allocated: <b>{fmt(parts.total)} NXBC</b></div><div className="text-sm">Reserved / unallocated: <b className={Math.abs(tokens-parts.total)>1e-9?'text-rose-300':'text-emerald-300'}>{fmt(Math.max(0,tokens-parts.total))} NXBC</b></div>{totalOk?<div className="mt-2 flex items-center gap-2 text-xs font-bold text-emerald-300"><CheckCircle2 size={15}/>100% allocation complete.</div>:<div className="mt-2 text-xs font-bold text-rose-300">Please allocate 100% of this purchase to eligible future phases and/or DEX/LIVE.</div>}</div>
   {error&&<div className="rounded-xl border border-rose-500/40 bg-rose-500/10 p-3 text-sm font-bold text-rose-200">{error}</div>}
   <button onClick={confirm} disabled={!can} className={`w-full rounded-2xl py-4 font-black flex justify-center items-center gap-2 ${can?'bg-gradient-to-r from-amber-400 via-orange-400 to-cyan-300 text-black':'bg-slate-700 text-slate-400'}`}>{busy?'PROCESSING...':<><Lock size={18}/>CONFIRM & PAY ${purchaseUsd.toFixed(2)}<ArrowRight size={18}/></>}</button>
  </div></div></div>;
};
export default BuyTokenModal;
